### ISSUE TITLE
need help with API usage

### ISSUE THREAD

**Issue by eschava** [alankan886/SuperMemo2#11]
Is it possible that the next review_date is today? Like Anki does when the answer is "Again" (I don't know what it means in the SM2 terms)

**Comment by alankan886** [comment]
Hey @eschava,

From what I understand, Anki is a modified version of SM-2 algorithm, and reviewing on the same day is part of the modification, [this](https://faqs.ankiweb.net/what-spaced-repetition-algorithm.html) is a pretty good read for the changes Anki made.

I can't find where I read this answer, but I remember reading an answer to a question on [SuperMemopedia](https://supermemopedia.com/wiki/Main_Page) that the author doesn't like the interval going lower than a day. And it seems like his algorithms are set to increment the interval by day/days (http://supermemopedia.com/wiki/Which_interval_do_you_want_to_use).

I did think about having a modification mode, giving users more flexibility, like allowing users to set the intervals for repetition at 1 and repetition at 2 (which are 1 and 6 atm), and that can allow users to review on the same day after a failed recall. But I don't have an exact plan for that atm.
