### ISSUE TITLE
Interval Input

### ISSUE THREAD

**Issue by TimeTraveller-ZEN** [alankan886/SuperMemo2#14]
Thank you for your great work. I have a problem.

## Scenario:

1. June 25: After review, sm2 returns: `SMTwo(easiness=2, interval=2, repetitions=5, review_date=datetime.date(2024, 6, 27))`
2. June 27 - June 29: I forgot to review.
3. June 30: I remember to study. However,

## Question:
What should I input on June 30 to get the new data (if the quality is 3)?
A. `SMTwo(easiness=2, interval=2, repetitions=5).review(3)`
B. `SMTwo(easiness=2, interval=5, repetitions=5).review(3)`
C. Other way to deal with the delay?

**Comment by alankan886** [comment]
Hello again @TimeTraveller-ZEN,

So I would not change the interval value, take whatever was returned previously, but specify the review_date.

```
sm2 = SMTwo.first_review()
sm2.review(3, review_date="2024-06-30")
```

You can also specify a different date format like "%m-%d-%Y" (mon_day_year) or "%d-%m-%Y" (day_month_year) by doing the following, but it's default to the format of year-month-day:

```
from supermemo2 import mon_day_year, day_month_year

sm2 = SMTwo.first_review()
sm2.review(3, review_date="06-30-2024", date_fmt=mon_day_year)
# or
sm2.review(3, review_date="30-06-2024", date_fmt=day_month_year)
```

Hope this helps!

**Comment by TimeTraveller-ZEN** [comment]
Thank you Alan again 👍
