### ISSUE TITLE
Dict type

### ISSUE THREAD

**Issue by TimeTraveller-ZEN** [alankan886/SuperMemo2#15]
> review( quality, review_date=None, date_fmt=None )
>Return Type: Dict

The review method returns the following:

```python
SMTwo(easiness=2.0799999999999996, interval=14, repetitions=3, review_date=datetime.date(2024, 7, 4))
```

However, I thought it would return a dict like this:
```python
{"easiness": 2.0799999999999996, "interval": 14, "repetitions": 3, "review_date": "2024, 7, 4"}
```
Am I doing something wrong? I have seen in older versions that methods like SMTwo.json() or SMTwo.dict() can be used to get a common dictionary type. Could you please confirm if my approach is correct or suggest the best way to achieve this?

**Comment by alankan886** [comment]
Hi @TimeTraveller-ZEN,

I think I forgot to update that part of the doc, it is expected to return a SMTwo object (might not be the best design now thinking about it). As of now, you can probably use the following snippet to turn the object into a dictionary, you should have attrs installed when install supermemo2.

```
from attrs import asdict

review = SMTwo(easiness=2.36, interval=1, repetitions=1, review_date=datetime.date(2024, 6, 22))
print(asdict(review))
# should print {'easiness': 2.36, 'interval': 1, 'repetitions': 1, 'review_date': datetime.date(2024, 6, 22)}
```

I'm going to think more on the design with use cases, maybe it's time to update this and improve the usability.

**Comment by TimeTraveller-ZEN** [comment]
Thank you very much :D
