### ISSUE TITLE
Can't Import supermemo2.models

### ISSUE THREAD

**Issue by Eikosa** [alankan886/SuperMemo2#5]
```
>>> import supermemo2.models
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'supermemo2.models'
```

**Comment by alankan886** [comment]
Ah good catch again @Eikosa,

I think a small fix of adding `from .models import SMTwo` under supermemo2/\__init__.py should fix this.

I will be working on those fixes and some updates this weekend, but the fixes are open to grab.

Thanks again!
