### ISSUE TITLE
E-Factor not calculated when q < 3 

### ISSUE THREAD

**Issue by alankan886** [alankan886/SuperMemo2#8]
I had some misunderstanding of the [explanation of the algorithm](https://www.supermemo.com/en/archives1990-2015/english/ol/sm2), EF factor should always be calculated for every quality value.

I thought `If the quality response was lower than 3 then start repetitions for the item from the beginning without changing the E-Factor` means not to calculate a new EF factor, but it really means reset the repetitions and keep the new E-Factor.

**Comment by Zhuo-Ren** [comment]
I am also very curious about this issue. In your code, you keep updating this E-Factor, regardless of whether the score is less than 3. Is there any relevant evidence? I can't get the corresponding paper.

**Comment by alankan886** [comment]
Hey @Zhuo-Ren,

Thanks for the comment. So my changes are based on the [algorithm description](https://www.supermemo.com/en/archives1990-2015/english/ol/sm2), the [implementation](https://www.supermemo.com/en/archives1990-2015/english/ol/sm2source) and an answer I got from emailing help2021@supermemo.org.

And it seems like if E-Factor doesn't update when q is less than 3, then 0 to 2 as q would be making identical impacts.

But definitely correct me if you think I'm missing something, and let me know if this makes sense.

**Comment by Zhuo-Ren** [comment]
Thanks for your replay @alankan886. 
I think you are right after reading the [delphi implementation](https://www.supermemo.com/en/archives1990-2015/english/ol/sm2source) that you mentioned. It helps alot. 😄

**Comment by alankan886** [comment]
@Zhuo-Ren I'm glad I can help!
